server:
  port: 8081

# satoken 部分
sa-token:
  token-name: size-token
  # 默认30天 -1 永久有效
  timeout: 2592000
  active-timeout: -1 # 不限制 永不冻结
  is-concurrent: true # 允许同一账号多地登陆
  is-share: false # 不允许账号并发
  token-style: uuid # 默认 uuid 可取值 uuid  simple-uuid random-32 random-64 random-128
  is-log: true # 开启日志

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/size-satoken-demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: linsz99@  # 注意修改
    type: com.zaxxer.hikari.HikariDataSource

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.size.springboot3.entity
  global-config:
    db-config:
      id-type: auto
  camel-case-to-underline: true